const initialize_modules = () => {
    MODULES = {
        PROCESS_EDIT_MESSAGE: require(WA_MODULES.PROCESS_EDIT_MESSAGE),
        PROCESS_RENDERABLE_MESSAGES: require(WA_MODULES.PROCESS_RENDERABLE_MESSAGES),
        MESSAGES_RENDERER: require(WA_MODULES.MESSAGES_RENDERER),
        PROTOBUF_HOOK: require(WA_MODULES.PROTOBUF_HOOK),
        QUERY_GROUP: require(WA_MODULES.QUERY_GROUP),
        SEND_MESSAGE: require(WA_MODULES.SEND_MESSAGE),
        OPEN_CHAT: require(WA_MODULES.OPEN_CHAT),
        HANDLE_RECEIPT: require(WA_MODULES.HANDLE_RECEIPT),
        RECEIPT_BATCHER: require(WA_MODULES.RECEIPT_BATCHER),
        WEB_ACK: require(WA_MODULES.WEB_ACK),
        WID_FACTORY: require(WA_MODULES.WID_FACTORY),
        SERVER_PROPS: require(WA_MODULES.SERVER_PROPS),
    };
    console.log('Modules have been loaded successfully!');
};
